apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpbarik
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cpbarik
    spec:
      containers:
      - name: cpbarik
        image: cpbarik1/jenkin-docker-helm-kubernetes
        imagePullPolicy: Always
        ports:
        - containerPort: 80

