apiVersion: v1
kind: Service
metadata:
  name: cpbarik-service
  labels:
     app: cpbarik
spec:
  selector:
    app: cpbarik
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200

